filebeat.inputs:
  # JSON логи приложения
  - type: log
    enabled: true
    paths:
      - /var/log/fraud-detection/*.json.log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message
    fields:
      service: fraud-detection
      log_type: application
    fields_under_root: true

  # Docker контейнеры
  - type: container
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    json.message_key: log
    json.keys_under_root: true
    json.add_error_key: true
    processors:
      - add_docker_metadata: ~
    fields:
      log_type: docker
    fields_under_root: true

  # Системные логи
  - type: log
    enabled: true
    paths:
      - /var/log/syslog
      - /var/log/messages
    fields:
      log_type: system
    fields_under_root: true

# ===========================================
# Настройки общие
# ===========================================
processors:
  # Добавляем метаданные Kubernetes / Docker (если есть)
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_locale:
      format: offset

# ===========================================
# Модули Filebeat (при необходимости)
# ===========================================
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# ===========================================
# Output: Loki (через Promtail или напрямую)
# ===========================================
# Если логи отправляются напрямую в Loki:
#output.loki:
#  hosts: ["http://loki:3100"]
#  tenant_id: "fraud-detection"
#  labels:
#    job: "filebeat"
#    environment: "production"
#  batch:
#    size: 1048576
#    timeout: 5s

# ===========================================
# Output: Logstash (предпочтительно для Graylog)
# ===========================================
output.logstash:
  hosts: ["graylog:5044"]
  ssl.enabled: false

# ===========================================
# Logging самого Filebeat
# ===========================================
logging:
  level: info
  to_files: true
  to_syslog: false
  files:
    path: /var/log/filebeat
    name: filebeat
    keepfiles: 7
    permissions: 0644
