version: '3.8'

services:
  # Основное приложение
  fraud-detection-app:
    build: .
    container_name: fraud-detection-app
    environment:
      - ENVIRONMENT=production
      - LOG_DIR=/app/logs
      - LOG_LEVEL=INFO
      # Подключение к Graylog
      - GRAYLOG_HOST=graylog
      - GRAYLOG_PORT=12201
      # Подключение к Prometheus
      - METRICS_ENABLED=true
      - METRICS_PORT=9090
    volumes:
      - ./logs:/app/logs
      - app-logs:/app/logs
    ports:
      - "8000:8000"
      - "9090:9090"  # Prometheus metrics
    networks:
      - fraud-net
    depends_on:
      - graylog
      - prometheus
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
        tag: "fraud-detection-app"

  # Graylog для централизованного логирования
  graylog:
    image: graylog/graylog:5.0
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918  # admin
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
    ports:
      - "9000:9000"   # Graylog web interface
      - "12201:12201/udp"  # GELF UDP
      - "12201:12201/tcp"  # GELF TCP
      - "1514:1514"   # Syslog TCP
      - "1514:1514/udp"  # Syslog UDP
    volumes:
      - graylog-data:/usr/share/graylog/data
      - graylog-journal:/usr/share/graylog/data/journal
    networks:
      - fraud-net
    depends_on:
      - mongodb
      - elasticsearch
    restart: unless-stopped

  # MongoDB для Graylog
  mongodb:
    image: mongo:6.0
    container_name: graylog-mongodb
    volumes:
      - mongodb-data:/data/db
    networks:
      - fraud-net
    restart: unless-stopped

  # Elasticsearch для Graylog
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: graylog-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - fraud-net
    restart: unless-stopped

  # Prometheus для метрик
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9091:9090"
    networks:
      - fraud-net
    restart: unless-stopped

  # Grafana для визуализации
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - fraud-net
    depends_on:
      - prometheus
      - graylog
    restart: unless-stopped

  # Loki для логов (альтернатива Graylog)
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - fraud-net
    restart: unless-stopped

  # Promtail для сбора логов в Loki
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./config/promtail-config.yml:/etc/promtail/config.yml
      - ./logs:/var/log/fraud-detection
      - app-logs:/var/log/fraud-detection
    command: -config.file=/etc/promtail/config.yml
    networks:
      - fraud-net
    depends_on:
      - loki
    restart: unless-stopped

  # Filebeat для отправки логов в Elasticsearch (опционально)
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: filebeat
    user: root
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/var/log/fraud-detection:ro
      - app-logs:/var/log/fraud-detection:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: filebeat -e -strict.perms=false
    networks:
      - fraud-net
    depends_on:
      - elasticsearch
    restart: unless-stopped

networks:
  fraud-net:
    driver: bridge

volumes:
  app-logs:
  graylog-data:
  graylog-journal:
  mongodb-data:
  elasticsearch-data:
  prometheus-data:
  grafana-data:
  loki-data:
