import json
import os
from logger.utils import generate_correlation_id

def test_log_contains_correlation_id(logger_instance):
    logger = logger_instance
    correlation_id = generate_correlation_id()
    logger.info("Operation started", extra={"correlation_id": correlation_id})

    log_file = os.environ["LOGGER_PATH"]
    with open(log_file, "r", encoding="utf-8") as f:
        data = json.loads(f.readline())

    assert data["correlation_id"] == correlation_id

def test_autogenerated_correlation_id(logger_instance):
    logger = logger_instance
    logger.info("Autogenerated ID")

    log_file = os.environ["LOGGER_PATH"]
    with open(log_file, "r", encoding="utf-8") as f:
        data = json.loads(f.readline())

    assert "correlation_id" in data
    assert len(data["correlation_id"]) > 0
