groups:
  - name: fraud_detection_alerts
    interval: 30s
    rules:
      # Высокая частота ошибок
      - alert: HighErrorRate
        expr: rate(transaction_errors_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
          component: processing
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} per second (threshold: 0.05)"

      # Медленная обработка
      - alert: SlowTransactionProcessing
        expr: histogram_quantile(0.95, rate(transaction_processing_duration_seconds_bucket[5m])) > 5
        for: 5m
        labels:
          severity: warning
          component: processing
        annotations:
          summary: "Slow transaction processing"
          description: "95th percentile processing time is {{ $value }}s"

      # Большая очередь
      - alert: HighQueueSize
        expr: queue_size > 1000
        for: 10m
        labels:
          severity: warning
          component: queue
        annotations:
          summary: "Queue size is growing"
          description: "Queue size is {{ $value }} (threshold: 1000)"

      # Падение rate обработки
      - alert: LowProcessingRate
        expr: rate(transactions_processed_total[5m]) < 10
        for: 15m
        labels:
          severity: warning
          component: processing
        annotations:
          summary: "Low processing rate"
          description: "Processing only {{ $value }} transactions per second"
