filebeat.inputs:
  # JSON логи приложения
  - type: log
    enabled: true
    paths:
      - /var/log/fraud-detection/*.json.log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message
    fields:
      service: fraud-detection
      log_type: application
    fields_under_root: true

  # Docker контейнеры
  - type: container
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"

# Обработчики
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true

# Вывод в Elasticsearch
output.elasticsearch:
  hosts: ['elasticsearch:9200']
  indices:
    - index: "fraud-detection-app-%{+yyyy.MM.dd}"
      when.equals:
        fields.log_type: "application"
    - index: "fraud-detection-transactions-%{+yyyy.MM.dd}"
      when.contains:
        log.file.path: "transactions"
    - index: "fraud-detection-audit-%{+yyyy.MM.dd}"
      when.contains:
        log.file.path: "audit"

# Настройки логирования Filebeat
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

