server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Сбор JSON логов приложения
  - job_name: fraud-detection-json
    static_configs:
      - targets:
          - localhost
        labels:
          job: fraud-detection
          __path__: /var/log/fraud-detection/*.json.log
    pipeline_stages:
      # Парсим JSON
      - json:
          expressions:
            timestamp: timestamp
            level: level
            component: component
            message: message
            correlation_id: correlation_id
            transaction_id: transaction_id
      # Извлекаем timestamp
      - timestamp:
          source: timestamp
          format: RFC3339
      # Добавляем labels
      - labels:
          level:
          component:
          correlation_id:
          transaction_id:

  # Сбор логов транзакций
  - job_name: fraud-detection-transactions
    static_configs:
      - targets:
          - localhost
        labels:
          job: fraud-detection-transactions
          __path__: /var/log/fraud-detection/transactions.json.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            transaction_id: transaction_id
            amount: extra_fields.amount
            status: extra_fields.status
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          transaction_id:
          status:

  # Сбор audit логов
  - job_name: fraud-detection-audit
    static_configs:
      - targets:
          - localhost
        labels:
          job: fraud-detection-audit
          __path__: /var/log/fraud-detection/audit.json.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            user_id: extra_fields.user_id
            action: extra_fields.action
            resource_type: extra_fields.resource_type
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          user_id:
          action:
          resource_type:

